config/routes.rb
Rails.application.routes.draw do

  concern :paginatable do
    get '(page/:page)', :action => :index, :on => :collection, :as => ''
  end

  scope "(:locale)", locale: /en|fr/ do
    resources :events

    resources :organizations

    resources :references, except: [:index, :show]

    resources :messages, only: [:new, :create]

    resources :conversations, only: [:index, :show, :update, :destroy]

    resources :profiles

    resources :requests, concerns: :paginatable do
      collection do
        get 'search/(page/:page)', :action => :search, :as => 'search'
      end
    end

    resources :offers, concerns: :paginatable do
      collection do
        get 'search/(page/:page)', :action => :search, :as => 'search'
      end
    end

    resources :caps_transactions, only: [:create]

    resources :hubs

    resources :community_offers, only: [:new, :create]

    devise_for :users, controllers: { invitations: 'users/invitations' }
    resources :users, only: [:edit, :update, :destroy]

    get 'pods/home', controller: :pods, action: :home, as: :home_pod
    resources :pods do
    end

    get 'home', to: 'static_page#home'
    get 'alpha_signup', to: 'static_page#alpha_signup'
    get 'tou', to: 'static_page#tou', as: :tou
    get 'help', to: 'static_page#help', as: :help

    get '/:locale', to: 'static_page#home'
    root 'static_page#home'
  end

  namespace :admin do
    get '/generate_caps', to: 'caps#new'
    post '/generate_caps', to: 'caps#create'
  end

  ActiveAdmin.routes(self)

  
  get '/faq', to: redirect("https://joatu.wordpress.com/faq/")
  get '/press', to: redirect("https://joatu.wordpress.com/press/")
  get '/volunteer', to: redirect("https://joatu.wordpress.com/volunteer/")
  get '/community', to: redirect("https://joatu.wordpress.com/community/")
  get '/contact', to: redirect("https://joatu.wordpress.com/contact/")
  get '/blog', to: redirect("http://joatu.wordpress.com/")
  get '/how-i-thrived-on-a-basic-income-of-11000-last-year-in-montreal', to: redirect("https://joatu.wordpress.com/2015/01/29/how-i-thrived-on-a-basic-income-of-11000-last-year-in-montreal/")
  get '/grass-to-gardens-joatus-community-initiative', to: redirect("https://joatu.wordpress.com/2014/09/04/grass-to-gardens-joatus-community-initiative/")
  get '/peoples-social-forum-2014-space-for-change', to: redirect("https://joatu.wordpress.com/2014/08/27/peoples-social-forum-2014-space-for-change/")
  get '/the-other-side-of-basic-income-basic-jobs', to: redirect("https://joatu.wordpress.com/2014/07/28/the-other-side-of-basic-income-basic-jobs/")
  get '/what-i-learned-at-the-hopex-hacker-conference', to: redirect("https://joatu.wordpress.com/2014/07/23/what-i-learned-at-the-hopex-hacker-conference/")
  get '/joatu-relaunches-its-campaign-3500-to-goal', to: redirect("https://joatu.wordpress.com/2014/07/10/joatu-relaunches-its-campaign-3500-to-goal/")
  get '/press-release-apr15-2014-crowd-funding-campaign-launch', to: redirect("https://joatu.wordpress.com/2014/04/15/press-release-apr15-2014-crowd-funding-campaign-launch/")
  get '/joatu-org-invitation', to: redirect("https://joatu.wordpress.com/2015/02/02/joatu-org-opens-up-invitations/")
end

app/models/request.rb
class Request < OfferOrRequest
  default_scope { where(offer_or_request: 'request') }

  def self.policy_class
    RequestPolicy
  end

  def self.valid_types
    descendants.map {|c| c.name }
  end

  def self.type_options
    descendants.inject({}) {|h, c| h[c.name.demodulize.titleize] = c.name.to_s; h}
  end
end

# This loads the request subclasses, so that we can call Request.descendents and
# get all the types.
Dir[Rails.root.join('app', 'models', 'request', '*.rb')].each {|file| require_dependency file }

app/models/request/knowledge.rb
class Request::Knowledge < Request
end

app/models/request/physical_goods.rb
class Request::PhysicalGoods < Request
end

app/models/request/skills_and_time.rb
class Request::SkillsAndTime < Request
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_request, only: [:show, :edit, :update, :destroy]
  before_action :set_search_options, only: [:index, :search]
  skip_after_action :verify_authorized, only: [:index, :search]

  respond_to :html

  SearchQuery = Struct.new(:search, :order_by, :types_filter) do include ActiveModel::Model; end

  def index
    @search_form = RequestSearchForm.new(SearchQuery.new)
    @search_form.save do |search_data|
      @user_requests = Request.search_results(search_data, current_user, PaginationOptions.new(params[:page]))
    end
    respond_with(@user_requests)
  end

  def show
    authorize @user_request
    @requester = @user_request.user
    @requester_offers = Offer.owned_by(@requester, PaginationOptions.new(params[:offers_page], 5))
    @requester_references = Reference.to_user(@requester, PaginationOptions.new(params[:references_page], 5))
    respond_with(@user_request)
  end

  def new
    @form = RequestForm.new(Request.new)
    @request_types = Request.type_options
    authorize @form.model
    respond_with(@user_request = @form)
  end

  def edit
    authorize @user_request
    @request_types = Request.type_options
    @user_request = RequestForm.new(@user_request)
  end

  def create
    @request_types = Request.type_options

    @form = RequestForm.new(Request.new(user: current_user))
    authorize @form.model
    if @form.validate(params[:request])
      if @form.visibility == :pod
        @form.model.pod = Pod.home_pod_for_user(current_user)
      else
        @form.model.pod = nil
      end
      @form.save
    end
    respond_with(@user_request = @form)
  end

  def update
    @request_types = Request.type_options

    @form = RequestForm.new(@user_request)
    authorize @form.model
    if @form.validate(params[:request])
      if @form.visibility == :pod
        @form.model.pod = Pod.home_pod_for_user(current_user)
      else
        @form.model.pod = nil
      end
      @form.save
    end
    respond_with(@user_request = @form)
  end

  def destroy
    authorize @user_request
    @user_request.destroy
    respond_with(@user_request)
  end

  def search
    params[:request_search] ||= {}
    @search_form = RequestSearchForm.new(SearchQuery.new)
    if @search_form.validate(params[:request_search])
      @search_form.save do |search_data|
        @user_requests = Request.search_results(search_data, current_user, PaginationOptions.new(params[:page]))
        render :index
      end
    else
      Rails.logger.debug "Errors: #{@search_form.errors.full_messages.inspect}"
      redirect_to requests_path
    end
  end

  private
    def set_request
      @user_request = Request.find(params[:id])
    end

    def set_search_options
      @order_options = {
        "Newest First" => :created_at_desc,
        "Oldest First" => :created_at_asc
      }
      @request_type_options = Request.type_options
    end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_form.html.haml
= simple_form_for(@user_request) do |f|
  = f.error_notification

  .form-inputs
    = f.input :type, collection: @request_types, as: :radio_buttons, label: "#{t('requests.type_label')}:"
    = f.input :title
    = f.input :description, as: :text
    = f.input :visibility, collection: {t('requests.visibility.global') => "global", t('requests.visibility.pod') => "pod"}, as: :select, label: "#{t('requests.visibility.label')}:"

  .form-actions
    = f.button :submit, class: 'pull-right btn-primary'

app/views/requests/_request.html.haml
= div_for request_model, class: "panel panel-default" do
  .panel-heading
    %h3.panel-title= request_model.title
  .panel-body
    = request_model.description
    .btn-group-sm.pull-right
      - if request_model.user.profile.present? && request_model.user.profile.id.present?
        = link_to profile_path(id: request_model.user.profile.id), class: 'btn btn-primary' do
          %span.glyphicon.glyphicon-user.pull-right
      = link_to new_message_path(receiver: request_model.user.id), class: 'btn btn-primary' do
        %span.glyphicon.glyphicon-envelope.pull-right
      = link_to request_path(request_model.id), class: 'btn btn-default' do
        %span.glyphicon.glyphicon-arrow-right.pull-right

app/views/requests/_request_list_item.html.haml
- request_model ||= request_list_item
%a.list-group-item.request-list-group-item{href: request_path(request_model), class: "#{request_model.type_class}"}
  %h4
    = request_model.title
    %br
    %small= t('requests.requester_label', requester: request_model.user.name)
  %p= truncate(request_model.description, length: 100)

app/views/requests/edit.html.haml
%h1= t('requests.editing_header')

= render 'form'

= link_to t('show'), @user_request
\|
= link_to t('back'), requests_path

app/views/requests/index.html.haml
.row.requests-list
  .col-sm-4
    .panel.panel-info
      .panel-heading
        %h2.text-center Search
      .panel-body
        = simple_form_for @search_form, url: search_requests_path, wrapper: :horizontal_form, html: {method: :get, class: 'form-horizontal'} do |f|
          = f.input :search, placeholder: t('requests.search_placeholder')
          = f.input :order_by, collection: @order_options
          = f.input :types_filter, collection: @request_type_options, as: :check_boxes, label: t('requests.types_filter_label'), wrapper: :horizontal_radio_and_checkboxes
          = f.button :submit, t('requests.search'), class: 'pull-right'

        .clearfix
        %br
        = link_to new_request_path, class: 'btn btn-success pull-right' do
          %i.glyphicon.glyphicon-plus
          = t('requests.new_link') 
  .col-sm-8
    .panel.panel-default
      .panel-heading
        %h1.text-center= t('requests.index_header')
      - if @user_requests.empty?
        .panel-body
          = t('requests.empty')
      .list-group
        = render partial: "requests/request_list_item", collection: @user_requests
        = paginate @user_requests

app/views/requests/new.html.haml
.row
  .col-sm-6.col-sm-offset-3
    .panel.panel-default
      .panel-heading
        %h1= t('requests.new_header')
      .panel-body
        = render 'form'

app/views/requests/show.html.haml
%p#notice= notice

.row
  .col-sm-6
    %h1
      = @user_request.title

      .pull-right
        - if Pundit.policy(current_user, @user_request).edit?
          = link_to t('edit'), edit_request_path(@user_request), class: 'btn btn-info'
        - if Pundit.policy(current_user, @user_request).destroy?
          = link_to t('destroy'), request_path(@user_request), method: :delete, class: 'btn btn-danger'
    .panel.panel-default
      .panel-heading= t('requests.description')
      .panel-body
        = @user_request.description
        .pull-right
          = link_to new_message_path(receiver: @user_request.user.id), class: 'btn btn-primary btn-large' do
            = t('requests.send_message', requester: @requester.profile.full_name)
  .col-sm-6
    .panel.panel-info
      .panel-heading
        = link_to profile_path(@requester.profile) do
          .media
            .media-left
              = gravatar_tag @requester, :profile
            .media-body.media-middle
              %h3= t('requests.requested_by.header', requester: @requester.profile.full_name)
      .panel-body
        %h4= "#{t('requests.requested_by.about_header')}:"
        %p
          = @requester.profile.about_me
        .row
          .col-sm-6
            .panel.panel-default
              .panel-heading= t('requests.requested_by.offers.header')
              .panel-body
                - if @requester_offers.empty?
                  %p= t('requests.requested_by.offers.has_no_offers', requester: @requester.profile.full_name)
                - else
                  %p= t('requests.requested_by.offers.has_open_offers', requester: @requester.profile.full_name)
              .list-group
                = render partial: 'offers/offer_list_item', collection: @requester_offers, as: :offer
                = paginate @requester_offers, param_name: :offers_page

          .col-sm-6
            .panel.panel-default
              .panel-heading= t('requests.requested_by.references_header')
              .list-group
                = render partial: 'references/reference_list_item', collection: @requester_references, as: :reference
                = paginate @requester_references, param_name: :references_page