config/routes.rb
Rails.application.routes.draw do

  concern :paginatable do
    get '(page/:page)', :action => :index, :on => :collection, :as => ''
  end

  scope "(:locale)", locale: /en|fr/ do
    resources :events

    resources :organizations

    resources :references, except: [:index, :show]

    resources :messages, only: [:new, :create]

    resources :conversations, only: [:index, :show, :update, :destroy]

    resources :profiles

    resources :requests, concerns: :paginatable do
      collection do
        get 'search/(page/:page)', :action => :search, :as => 'search'
      end
    end

    resources :offers, concerns: :paginatable do
      collection do
        get 'search/(page/:page)', :action => :search, :as => 'search'
      end
    end

    resources :caps_transactions, only: [:create]

    resources :hubs

    resources :community_offers, only: [:new, :create]

    devise_for :users, controllers: { invitations: 'users/invitations' }
    resources :users, only: [:edit, :update, :destroy]

    get 'pods/home', controller: :pods, action: :home, as: :home_pod
    resources :pods do
    end

    get 'home', to: 'static_page#home'
    get 'alpha_signup', to: 'static_page#alpha_signup'
    get 'tou', to: 'static_page#tou', as: :tou
    get 'help', to: 'static_page#help', as: :help

    get '/:locale', to: 'static_page#home'
    root 'static_page#home'
  end

  namespace :admin do
    get '/generate_caps', to: 'caps#new'
    post '/generate_caps', to: 'caps#create'
  end

  ActiveAdmin.routes(self)

  
  get '/faq', to: redirect("https://joatu.wordpress.com/faq/")
  get '/press', to: redirect("https://joatu.wordpress.com/press/")
  get '/volunteer', to: redirect("https://joatu.wordpress.com/volunteer/")
  get '/community', to: redirect("https://joatu.wordpress.com/community/")
  get '/contact', to: redirect("https://joatu.wordpress.com/contact/")
  get '/blog', to: redirect("http://joatu.wordpress.com/")
  get '/how-i-thrived-on-a-basic-income-of-11000-last-year-in-montreal', to: redirect("https://joatu.wordpress.com/2015/01/29/how-i-thrived-on-a-basic-income-of-11000-last-year-in-montreal/")
  get '/grass-to-gardens-joatus-community-initiative', to: redirect("https://joatu.wordpress.com/2014/09/04/grass-to-gardens-joatus-community-initiative/")
  get '/peoples-social-forum-2014-space-for-change', to: redirect("https://joatu.wordpress.com/2014/08/27/peoples-social-forum-2014-space-for-change/")
  get '/the-other-side-of-basic-income-basic-jobs', to: redirect("https://joatu.wordpress.com/2014/07/28/the-other-side-of-basic-income-basic-jobs/")
  get '/what-i-learned-at-the-hopex-hacker-conference', to: redirect("https://joatu.wordpress.com/2014/07/23/what-i-learned-at-the-hopex-hacker-conference/")
  get '/joatu-relaunches-its-campaign-3500-to-goal', to: redirect("https://joatu.wordpress.com/2014/07/10/joatu-relaunches-its-campaign-3500-to-goal/")
  get '/press-release-apr15-2014-crowd-funding-campaign-launch', to: redirect("https://joatu.wordpress.com/2014/04/15/press-release-apr15-2014-crowd-funding-campaign-launch/")
  get '/joatu-org-invitation', to: redirect("https://joatu.wordpress.com/2015/02/02/joatu-org-opens-up-invitations/")
end

app/models/pod.rb
class Pod < ActiveRecord::Base
  has_one :hub, through: :hub_organization_relation, source: :organization
  has_one :hub_organization_relation, class: PodHubRelation, dependent: :destroy

  has_many :members, through: :pod_memberships, source: :user
  has_many :pod_memberships

  def self.home_pod_for_user(user)
    PodMembership.home_membership_for_user(user).pod || UncreatedPod.new
  end

  # Returns the current "best pod" for the user, based on "our algorythm".
  # Really just tries to geocode a point from the user's postal code, and then
  # find any pods that focus on that point. If there's a match, the first pod
  # wins. Otherwise we return an instance of UncreatedPod.
  def self.best_for_user(user)
    return UncreatedPod.new if user.home_location.blank?

    pods = where("ST_Contains(focus_area, ST_PointFromText('POINT(#{user.home_location.x} #{user.home_location.y})'))")

    pods.first || UncreatedPod.new
  end

  def to_geojson
    return "" if self.new_record?

    feature = RGeo::GeoJSON::Feature.new(self.focus_area)
    RGeo::GeoJSON.encode(feature).to_json
  end

  def map_bounds
    min_x = min_y = 1000
    max_x = max_y = -1000
    self.focus_area.exterior_ring.points.each do |point|
      min_x = point.x if point.x < min_x
      min_y = point.y if point.y < min_y

      max_x = point.x if point.x > max_x
      max_y = point.y if point.y > max_y
    end

    [[min_y, min_x], [max_y, max_x]]
  end

  def hub_id
    hub.try(:id)
  end

  def hub_id=(val)
    self.hub = Organization.find(val)
  end
end

app/controllers/pods_controller.rb
class PodsController < ApplicationController
  before_filter :authenticate_user!

  # Show's the user's home pod.
  def home
    @display_add_offers_and_requests = true

    @pod = Pod.home_pod_for_user(current_user)
    @hub = @pod.hub
    @events = Event.available_for_pod(@pod, PaginationOptions.new(1, 3))
    authorize @pod, :show?
    render :show
  end
end

app/helpers/pods_helper.rb
module PodsHelper
end

app/views/pods/_form.html.haml
= simple_form_for(@pod) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :description
    = f.input :focus_area
    = f.input :hub_id

  .form-actions
    = f.button :submit

app/views/pods/edit.html.haml
%h1 Editing pod

= render 'form'

= link_to 'Show', @pod
\|
= link_to 'Back', pods_path

app/views/pods/index.html.haml
%h1 Listing pods

%table
  %thead
    %tr
      %th Name
      %th Description
      %th Focus area
      %th Hub
      %th
      %th
      %th
      
  %tbody
    - @pods.each do |pod|
      %tr
        %td= pod.name
        %td= pod.description
        %td= pod.focus_area
        %td= pod.hub_id
        %td= link_to 'Show', pod
        %td= link_to 'Edit', edit_pod_path(pod)
        %td= link_to 'Destroy', pod, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Pod', new_pod_path

app/views/pods/new.html.haml
%h1 New pod

= render 'form'

= link_to 'Back', pods_path

app/views/pods/show.html.haml
%h1
  = "#{t('pods.pod')}: "
  = @pod.name
.row
  .col-sm-8
    - if @display_add_offers_and_requests
      .alert.alert-info.alert-dismissible{role: "alert"}
        %button.close{type: "button", data: {dismiss: 'alert'}}
          %span{'aria-hidden' => true} &times;
        %strong
          = t('pods.few_offers_header')
        = t('pods.few_offers_content_html', offers_link: link_to(t('pods.offers_link_text'), new_offer_path, class: 'alert-link'), requests_link: link_to(t('pods.requests_link_text'), new_request_path, class: 'alert-link'))

    .panel.panel-primary
      .panel-heading
        %h3.panel-title
          = t('pods.about')
      .panel-body
        = @pod.description
    .panel.panel-default
      .panel-heading
        %h3.panel-title
          = t('pods.events')
      .panel-body
        - if @events.any?
          = "#{t('pods.events_intro', pod_name: @pod.name)}:"
        - else
          = t('pods.no_events_message')
      .list-group
        = render partial: "events/event_list_item", collection: @events
      
  .col-sm-4.hub
    .panel.panel-default
      .panel-heading
        %h3.panel-title
          = t('pods.map')
      .panel-body
        .pod-map.embed-responsive.embed-responsive-16by9{"data-map" => true, "data-geojson" => @pod.to_geojson, "data-bounds" => @pod.map_bounds }
          #pod-map.map-container
    - if @hub.present?
      .panel.panel-info
        .panel-heading
          %h3.panel-title
            = "#{t('pods.hub')}: "
            = @hub.name
        .panel-body
          = @hub.description