config/routes.rb
Rails.application.routes.draw do

  concern :paginatable do
    get '(page/:page)', :action => :index, :on => :collection, :as => ''
  end

  scope "(:locale)", locale: /en|fr/ do
    resources :events

    resources :organizations

    resources :references, except: [:index, :show]

    resources :messages, only: [:new, :create]

    resources :conversations, only: [:index, :show, :update, :destroy]

    resources :profiles

    resources :requests, concerns: :paginatable do
      collection do
        get 'search/(page/:page)', :action => :search, :as => 'search'
      end
    end

    resources :offers, concerns: :paginatable do
      collection do
        get 'search/(page/:page)', :action => :search, :as => 'search'
      end
    end

    resources :caps_transactions, only: [:create]

    resources :hubs

    resources :community_offers, only: [:new, :create]

    devise_for :users, controllers: { invitations: 'users/invitations' }
    resources :users, only: [:edit, :update, :destroy]

    get 'pods/home', controller: :pods, action: :home, as: :home_pod
    resources :pods do
    end

    get 'home', to: 'static_page#home'
    get 'alpha_signup', to: 'static_page#alpha_signup'
    get 'tou', to: 'static_page#tou', as: :tou
    get 'help', to: 'static_page#help', as: :help

    get '/:locale', to: 'static_page#home'
    root 'static_page#home'
  end

  namespace :admin do
    get '/generate_caps', to: 'caps#new'
    post '/generate_caps', to: 'caps#create'
  end

  ActiveAdmin.routes(self)

  
  get '/faq', to: redirect("https://joatu.wordpress.com/faq/")
  get '/press', to: redirect("https://joatu.wordpress.com/press/")
  get '/volunteer', to: redirect("https://joatu.wordpress.com/volunteer/")
  get '/community', to: redirect("https://joatu.wordpress.com/community/")
  get '/contact', to: redirect("https://joatu.wordpress.com/contact/")
  get '/blog', to: redirect("http://joatu.wordpress.com/")
  get '/how-i-thrived-on-a-basic-income-of-11000-last-year-in-montreal', to: redirect("https://joatu.wordpress.com/2015/01/29/how-i-thrived-on-a-basic-income-of-11000-last-year-in-montreal/")
  get '/grass-to-gardens-joatus-community-initiative', to: redirect("https://joatu.wordpress.com/2014/09/04/grass-to-gardens-joatus-community-initiative/")
  get '/peoples-social-forum-2014-space-for-change', to: redirect("https://joatu.wordpress.com/2014/08/27/peoples-social-forum-2014-space-for-change/")
  get '/the-other-side-of-basic-income-basic-jobs', to: redirect("https://joatu.wordpress.com/2014/07/28/the-other-side-of-basic-income-basic-jobs/")
  get '/what-i-learned-at-the-hopex-hacker-conference', to: redirect("https://joatu.wordpress.com/2014/07/23/what-i-learned-at-the-hopex-hacker-conference/")
  get '/joatu-relaunches-its-campaign-3500-to-goal', to: redirect("https://joatu.wordpress.com/2014/07/10/joatu-relaunches-its-campaign-3500-to-goal/")
  get '/press-release-apr15-2014-crowd-funding-campaign-launch', to: redirect("https://joatu.wordpress.com/2014/04/15/press-release-apr15-2014-crowd-funding-campaign-launch/")
  get '/joatu-org-invitation', to: redirect("https://joatu.wordpress.com/2015/02/02/joatu-org-opens-up-invitations/")
end

app/models/offer.rb
class Offer < OfferOrRequest
  default_scope { where(offer_or_request: 'offer') }

  def self.policy_class
    OfferPolicy
  end

  def self.valid_types
    descendants.map {|c| c.name }
  end

  def self.type_options
    descendants.inject({}) {|h, c| h[c.name.demodulize.titleize] = c.name.to_s; h}
  end
end

# This loads the offer subclasses, so that we can call Offer.descendents and
# get all the types.
Dir[Rails.root.join('app', 'models', 'offer', '*.rb')].each {|file| require_dependency file }

app/models/offer/knowledge.rb
class Offer::Knowledge < Offer
end

app/models/offer/physical_goods.rb
class Offer::PhysicalGoods < Offer
end

app/models/offer/skills_and_time.rb
class Offer::SkillsAndTime < Offer
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_offer, only: [:show, :edit, :update, :destroy]
  before_action :set_search_options, only: [:index, :search]
  skip_after_action :verify_authorized, only: [:index, :search]

  respond_to :html

  SearchQuery = Struct.new(:search, :order_by, :types_filter) do include ActiveModel::Model; end

  def index
    @search_form = OfferSearchForm.new(SearchQuery.new)
    @search_form.save do |search_data|
      @offers = Offer.search_results(search_data, current_user, PaginationOptions.new(params[:page]))
    end
    respond_with(@offers)
  end

  def show
    authorize @offer
    @offerer = @offer.user
    @offerer_requests = Request.owned_by(@offerer, PaginationOptions.new(params[:requests_page], 5))
    @offerer_references = Reference.to_user(@offerer, PaginationOptions.new(params[:references_page], 5))
    respond_with(@offer)
  end

  def new
    @form = OfferForm.new(Offer.new)
    @offer_types = Offer.type_options
    authorize @form.model
    respond_with(@offer = @form)
  end

  def edit
    authorize @offer
    @offer_types = Offer.type_options
    @offer = OfferForm.new(@offer)
  end

  def create
    @form = OfferForm.new(Offer.new(user: current_user))
    @offer_types = Offer.type_options
    authorize @form.model
    if @form.validate(params[:offer])
      if @form.visibility == :pod
        @form.model.pod = Pod.home_pod_for_user(current_user)
      else
        @form.model.pod = nil
      end
      @form.save
    end
    respond_with(@offer = @form)
  end

  def update
    @form = OfferForm.new(@offer)
    @offer_types = Offer.type_options
    authorize @form.model
    if @form.validate(params[:offer])
      if @form.visibility == :pod
        @form.model.pod = Pod.home_pod_for_user(current_user)
      else
        @form.model.pod = nil
      end
      @form.save
    end
    respond_with(@offer = @form)
  end

  def destroy
    authorize @offer
    @offer.destroy
    respond_with(@offer)
  end

  def search
    params[:offer_search] ||= {}
    @search_form = OfferSearchForm.new(SearchQuery.new)

    if @search_form.validate(params[:offer_search])
      @search_form.save do |search_data|
        @offers = Offer.search_results(search_data, current_user, PaginationOptions.new(params[:page]))
        render :index
      end
    else
      redirect_to offers_path
    end
  end

  private
    def set_offer
      @offer = Offer.find(params[:id])
    end

    def set_search_options
      @order_options = {
        "Newest First" => :created_at_desc,
        "Oldest First" => :created_at_asc
      }
      @offer_type_options = Offer.type_options
    end
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/offers/_form.html.haml
= simple_form_for(@offer) do |f|
  = f.error_notification

  .form-inputs
    = f.input :type, collection: @offer_types, as: :radio_buttons, label: "#{t('offers.type_label')}:"
    = f.input :title
    = f.input :description, as: :text
    = f.input :visibility, collection: {t('offers.visibility.global') => "global", t('offers.visibility.pod') => "pod"}, as: :select, label: "#{t('offers.visibility.label')}:"

  .form-actions
    = f.button :submit, class: 'pull-right btn-primary'

app/views/offers/_offer.html.haml
= div_for offer, class: "panel panel-default" do
  .panel-heading
    %h3.panel-title= offer.title
  .panel-body
    = offer.description
    .btn-group-sm.pull-right
      - if offer.user.profile.present? && offer.user.profile.id.present?
        = link_to profile_path(id: offer.user.profile.id), class: 'btn btn-primary' do
          %span.glyphicon.glyphicon-user.pull-right
      = link_to new_message_path(receiver: offer.user.id), class: 'btn btn-primary' do
        %span.glyphicon.glyphicon-envelope.pull-right
      = link_to offer_path(offer.id), class: 'btn btn-default' do
        %span.glyphicon.glyphicon-arrow-right.pull-right

app/views/offers/_offer_list_item.html.haml
- offer ||= offer_list_item
%a.list-group-item.offer-list-group-item{href: offer_path(offer), class: "#{offer.type_class}"}
  %h4
    = offer.title
    %br
    %small= t('offers.offerer_label', offerer: offer.user.name)
  %p= truncate(offer.description, length: 100)

app/views/offers/edit.html.haml
%h1= t('offers.editing_header')

= render 'form'

= link_to t('show'), @offer
\|
= link_to t('back'), offers_path

app/views/offers/index.html.haml
.row.offers-list
  .col-sm-4
    .panel.panel-info
      .panel-heading
        %h2.text-center Search
      .panel-body
        = simple_form_for @search_form, url: search_offers_path, wrapper: :horizontal_form, html: {method: :get, class: 'form-horizontal'} do |f|
          = f.input :search, placeholder: t('offers.search_placeholder')
          = f.input :order_by, collection: @order_options
          = f.input :types_filter, collection: @offer_type_options, as: :check_boxes, label: t('offers.types_filter_label'), wrapper: :horizontal_radio_and_checkboxes
          = f.button :submit, t('offers.search'), class: 'pull-right'

        .clearfix
        %br
        = link_to new_offer_path, class: 'btn btn-success pull-right' do
          %i.glyphicon.glyphicon-plus
          = t('offers.new_link') 
  .col-sm-8
    .panel.panel-default
      .panel-heading
        %h1.text-center= t('offers.index_header')
      - if @offers.empty?
        .panel-body
          = t('offers.empty')
      .list-group
        = render partial: "offers/offer_list_item", collection: @offers
        = paginate @offers

app/views/offers/index.js.erb
populate_modal(
    "<%= j render("offers/index", layout: false) %>",
    "<h2 class='modal-title'><%= t('offers.index_header') %></h2>"
    )

app/views/offers/new.html.haml
.row
  .col-sm-6.col-sm-offset-3
    .panel.panel-default
      .panel-heading
        %h1= t('offers.new_header')
      .panel-body
        = render 'form'

app/views/offers/show.html.haml
%p#notice= notice

.row
  .col-sm-6
    %h1
      = @offer.title

      .pull-right
        - if Pundit.policy(current_user, @offer).edit?
          = link_to t('edit'), edit_offer_path(@offer), class: 'btn btn-info'
        - if Pundit.policy(current_user, @offer).destroy?
          = link_to t('destroy'), offer_path(@offer), method: :delete, class: 'btn btn-danger'
    .panel.panel-default
      .panel-heading= t('offers.description')
      .panel-body
        = @offer.description
        .pull-right
          = link_to new_message_path(receiver: @offer.user.id), class: 'btn btn-primary btn-large' do
            = t('offers.send_message', offerer: @offerer.profile.full_name)
  .col-sm-6
    .panel.panel-info
      .panel-heading
        = link_to profile_path(@offerer.profile) do
          .media
            .media-left
              = gravatar_tag @offerer, :profile
            .media-body.media-middle
              %h3= t('offers.offered_by.header', offerer: @offerer.profile.full_name)
      .panel-body
        %h4= "#{t('offers.offered_by.about_header')}:"
        %p
          = @offerer.profile.about_me
        .row
          .col-sm-6
            .panel.panel-default
              .panel-heading= t('offers.offered_by.requests.header')
              .panel-body
                - if @offerer_requests.empty?
                  %p= t('offers.offered_by.requests.has_no_requests', offerer: @offerer.profile.full_name)
                - else
                  %p= t('offers.offered_by.requests.has_open_requests', offerer: @offerer.profile.full_name)
              .list-group
                = render partial: 'requests/request_list_item', collection: @offerer_requests, as: :request_model
                = paginate @offerer_requests, param_name: :requests_page

          .col-sm-6
            .panel.panel-default
              .panel-heading= t('offers.offered_by.references_header')
              .list-group
                = render partial: 'references/reference_list_item', collection: @offerer_references, as: :reference
                = paginate @offerer_references, param_name: :references_page