config/routes.rb
Rails.application.routes.draw do

  concern :paginatable do
    get '(page/:page)', :action => :index, :on => :collection, :as => ''
  end

  scope "(:locale)", locale: /en|fr/ do
    resources :events

    resources :organizations

    resources :references, except: [:index, :show]

    resources :messages, only: [:new, :create]

    resources :conversations, only: [:index, :show, :update, :destroy]

    resources :profiles

    resources :requests, concerns: :paginatable do
      collection do
        get 'search/(page/:page)', :action => :search, :as => 'search'
      end
    end

    resources :offers, concerns: :paginatable do
      collection do
        get 'search/(page/:page)', :action => :search, :as => 'search'
      end
    end

    resources :caps_transactions, only: [:create]

    resources :hubs

    resources :community_offers, only: [:new, :create]

    devise_for :users, controllers: { invitations: 'users/invitations' }
    resources :users, only: [:edit, :update, :destroy]

    get 'pods/home', controller: :pods, action: :home, as: :home_pod
    resources :pods do
    end

    get 'home', to: 'static_page#home'
    get 'alpha_signup', to: 'static_page#alpha_signup'
    get 'tou', to: 'static_page#tou', as: :tou
    get 'help', to: 'static_page#help', as: :help

    get '/:locale', to: 'static_page#home'
    root 'static_page#home'
  end

  namespace :admin do
    get '/generate_caps', to: 'caps#new'
    post '/generate_caps', to: 'caps#create'
  end

  ActiveAdmin.routes(self)

  
  get '/faq', to: redirect("https://joatu.wordpress.com/faq/")
  get '/press', to: redirect("https://joatu.wordpress.com/press/")
  get '/volunteer', to: redirect("https://joatu.wordpress.com/volunteer/")
  get '/community', to: redirect("https://joatu.wordpress.com/community/")
  get '/contact', to: redirect("https://joatu.wordpress.com/contact/")
  get '/blog', to: redirect("http://joatu.wordpress.com/")
  get '/how-i-thrived-on-a-basic-income-of-11000-last-year-in-montreal', to: redirect("https://joatu.wordpress.com/2015/01/29/how-i-thrived-on-a-basic-income-of-11000-last-year-in-montreal/")
  get '/grass-to-gardens-joatus-community-initiative', to: redirect("https://joatu.wordpress.com/2014/09/04/grass-to-gardens-joatus-community-initiative/")
  get '/peoples-social-forum-2014-space-for-change', to: redirect("https://joatu.wordpress.com/2014/08/27/peoples-social-forum-2014-space-for-change/")
  get '/the-other-side-of-basic-income-basic-jobs', to: redirect("https://joatu.wordpress.com/2014/07/28/the-other-side-of-basic-income-basic-jobs/")
  get '/what-i-learned-at-the-hopex-hacker-conference', to: redirect("https://joatu.wordpress.com/2014/07/23/what-i-learned-at-the-hopex-hacker-conference/")
  get '/joatu-relaunches-its-campaign-3500-to-goal', to: redirect("https://joatu.wordpress.com/2014/07/10/joatu-relaunches-its-campaign-3500-to-goal/")
  get '/press-release-apr15-2014-crowd-funding-campaign-launch', to: redirect("https://joatu.wordpress.com/2014/04/15/press-release-apr15-2014-crowd-funding-campaign-launch/")
  get '/joatu-org-invitation', to: redirect("https://joatu.wordpress.com/2015/02/02/joatu-org-opens-up-invitations/")
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  has_many :memberships, class: OrganizationMembership
  has_many :members, through: :memberships, source: :user

  composed_of :address, mapping: %w(address_json to_json)

  # Not strictly necessary to specify the currency is caps here, as the app
  # default is caps, but this keeps things explicit, and doesn't hurt.
  monetize :caps_cents, with_currency: :caps 
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController

  private

    def organization_params
      params.require(:organization).permit(:name, :description, :latlng)
    end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.haml
= simple_form_for(@organization) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :description
    = f.input :latlng

  .form-actions
    = f.button :submit

app/views/organizations/edit.html.haml
%h1 Editing organization

= render 'form'

= link_to 'Show', @organization
\|
= link_to 'Back', organizations_path

app/views/organizations/index.html.haml
%h1 Listing organizations

%table
  %thead
    %tr
      %th Name
      %th Description
      %th Latlng
      %th
      %th
      %th
      
  %tbody
    - @organizations.each do |organization|
      %tr
        %td= organization.name
        %td= organization.description
        %td= organization.latlng
        %td= link_to 'Show', organization
        %td= link_to 'Edit', edit_organization_path(organization)
        %td= link_to 'Destroy', organization, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Organization', new_organization_path

app/views/organizations/new.html.haml
%h1 New organization

= render 'form'

= link_to 'Back', organizations_path

app/views/organizations/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @organization.name
%p
  %b Description:
  = @organization.description
%p
  %b Latlng:
  = @organization.latlng

= link_to 'Edit', edit_organization_path(@organization)
\|
= link_to 'Back', organizations_path